// <auto-generated />
namespace Reminder.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PhotoImageTypeChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PhotoImageTypeChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201811201438350_PhotoImageTypeChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
